name: DevSecOps CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run ESLint for code linting
      - name: Run ESLint
        run: npm run lint

      # Run unit tests with Jest
      - name: Run tests with Jest
        run: npm run test

      # Build Docker container
      - name: Build and run Docker container
        run: |
          docker build -t customer-payments-backend .
          docker run -d -p 3000:3000 customer-payments-backend

      # Run OWASP ZAP security scan
      - name: Run OWASP ZAP security scan
        uses: zaproxy/action-full-scan@v0.6.0
        with:
          target: 'http://localhost:3000'
          docker-name: 'owasp/zap2docker-stable'
